[tool.isort]
profile = 'black'
line_length = 100
py_version = 310
skip = [".gitignore", ".dockerignore"]

[tool.black]
line-length = 100
target-version = ['py310']
experimental-string-processing = true
verbose = true